### ISSUE TITLE
Failed to fetch 'packages.ros.org'

### ISSUE THREAD

**Issue by hhadzem** [dinkoosmankovic/SPEARDocker#1]
E: Failed to fetch https://packages.ros.org/ros/ubuntu/pool/main/r/ros-melodic-ompl/ros-melodic-ompl_1.4.2-5bionic.20191212.045602_abd64.deb Temporary failure resolving 'packages.ros.org'
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
ERROR: the following rosdeps failed to install apt:command [apt-get install -y ros-melodic-ompl] failed

Managed to resolve the problem by adding: **RUN : apt-get update** before installing catkin-tools. 

OS: Ubuntu 18.04.
Docker version: 19.03.8

**Comment by dinkoosmankovic** [comment]
Yes, ROS repos are not updated with one apt-get for some reason when done within docker.
